{% set version = "0.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lotri
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lotri_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lotri/lotri_{{ version }}.tar.gz
  sha256: 9a8e17d549e9d3ff9fdc246788c7569edae8e562bf7e9eeec79962fcbd2d26d1

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-crayon
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-crayon

test:
  commands:
    - $R -e "library('lotri')"           # [not win]
    - "\"%R%\" -e \"library('lotri')\""  # [win]

about:
  home: https://github.com/nlmixrdevelopment/lotri
  license: GPL-2.0-or-later
  summary: Provides a simple mechanism to specify a symmetric block diagonal matrices (often used for covariance matrices).  This is based on the domain specific language implemented in 'nlmixr' but expanded to create matrices in R generally instead of specifying parts of matrices to estimate.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lotri
# Title: A Simple Way to Specify Symmetric, Block Diagonal Matrices
# Version: 0.2.2
# Authors@R: c(person("Matthew L.","Fidler", role = c("aut", "cre"), email = "matthew.fidler@gmail.com", comment=c(ORCID="0000-0001-8538-6691")))
# Maintainer: Matthew L. Fidler <matthew.fidler@gmail.com>
# Description: Provides a simple mechanism to specify a symmetric block diagonal matrices (often used for covariance matrices).  This is based on the domain specific language implemented in 'nlmixr' but expanded to create matrices in R generally instead of specifying parts of matrices to estimate.
# Depends: R (>= 3.4.0)
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: true
# Imports: methods, utils, stats
# Suggests: testthat, covr, knitr, rmarkdown, Matrix, microbenchmark, ggplot2
# NeedsCompilation: yes
# Biarch: true
# RoxygenNote: 7.1.0
# VignetteBuilder: knitr
# BugReports: https://github.com/nlmixrdevelopment/lotri/issues
# URL: https://github.com/nlmixrdevelopment/lotri
# Packaged: 2020-05-29 20:30:35 UTC; FIDLEMA3
# Author: Matthew L. Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>)
# Repository: CRAN
# Date/Publication: 2020-05-29 21:20:03 UTC
